### PR TITLE
Pull request for tests

### PR DESCRIPTION
**Pull request by Steap**
Tests: bump the target coverage percentage.
Remove NPM implementation.
Use a single _pkgname method for all package types.
Add tests for the jinja2_reqformat methods.

### CODE REVIEW

**Review by mojca — APPROVED** [review]
I didn't test yet, but it all looks good to me.

**Review by reneeotten — APPROVED** [review]
thanks @Steap!

**Comment by Steap** [comment]
Can't remember what our merge policy was, two approvals means I can press that big green button? :)

**Comment by mojca** [comment]
No particular merge policy. It depends on how confident you are in your changes and whether you want to get an approval from someone else.

In the main ports tree we try to respect 72-hour window for the official maintainer to respond, but this is basically the work between @Korusuke , you and @reneeotten, so whatever you feel makes sense can be used here ...

**Review by Korusuke — APPROVED** [review]

**Comment by Korusuke** [comment]
thanks @Steap

**Pull request merged**
