### PR TITLE
Add coverage and update azure config

### PR DESCRIPTION
**Pull request by Korusuke**
This addresses Issue #8 

I have added coverage but as of now, it will fail as the pass criteria is 90% and till now the coverage is at 65%.

### CODE REVIEW

**Comment by Steap** [comment]
I would like this PR to be split into two different commits.

You can put the threshold at 60% in .coveragerc, and add more tests later.

**Comment by reneeotten** [comment]
I agree with @Steap, the Azure part should be in a different commit. 

You should for sure take a look at the Python versions that you have selected in the ``` azure-pipelines.yml```, ```upt``` will only work with Python >= 3.6. Additionally, I don't see you installing ```upt```, the frontends and ```upt-macports``` backend, so it's not really surprising that the tests fail ;) [edit: sorry, ignore that last comment ```tox``` should take care of this]

The idea of using Azure for the ```macports-port``` repository was that it allows for longer builds (Travis has a maximum of 50 minutes), which is important for ports that can take a long time to build. However, the tests here are finished very quickly so we'll never run into timeout issues with Travis; thinking about this a bit more, perhaps there is no reason to actually run the tests on Azure as well?

**Comment by mojca** [comment]
A few notes about Azure. For the ports it was absolutely critical to enable it as Travis is basically useless most of the time. But at the same time Travis fired most of their developers, so in my opinion it's only a question of time when they shut down for free projects. It absolutely doesn't hurt to have both enabled.

I certainly consider it optional to have two different services enabled, but now that the code is there, there should be no reason not to use it.

Also, there's nothing wrong with running the tests on Ubuntu (that is: both GNU Linux and macOS). Optional of course, but if it's just a matter of two lines in configuration, it cannot hurt to test on both.

**Comment by Korusuke** [comment]
As suggested I have done the following changes:
- Split into two commits
- Change threshold to 60
- Add macOS and ubuntu both for py36 and py37

Now the checks are passing :) so I guess this commit may be good to merge.

**Review by reneeotten — APPROVED** [review]

**Comment by reneeotten** [comment]
@Steap - are you okay with merging this? If I don't hear otherwise, I'll merge this tomorrow morning.

**Comment by Steap** [comment]
I trust with you the Azure stuff :)

**Pull request merged**
